name: Flutter Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Flutter 3.22.0
        run: |
          curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.22.0-stable.zip
          unzip flutter_macos_3.22.0-stable.zip
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          flutter precache

      - name: Confirm Dart & Flutter versions
        run: |
          flutter --version
          dart --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build IPA (or APK)
        run: flutter build ipa --release
